In [1]:
try:
    import torch
except ImportError as e:
    print ('installing PyTorch')
    !pip install -q -U torch watermark  # module doesn't exist, deal with it.
    


Pytorch is an open source machine learning framework that accelerates the path from research prototyping to production deployment.

## PyTorch ❤ NumPy

Pytorch is similar to Numpy. If you have good skills in Numpy then Pytorch will be a piece of cake for you. If not, don't worry, you will learn along the way!!

Let's start with something simple:

In [2]:
import torch
import numpy as np

In [3]:
x = np.array([1, 2])
y = np.array([3, 4])

In [4]:
x, y

(array([1, 2]), array([3, 4]))

In [5]:
z=x+y
z

array([4, 6])

Now let's do the same thing using Pytorch!!

In [6]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
x, y

(tensor([1, 2]), tensor([3, 4]))

Now we can simply add these 2 just like we did in the case of Numpy arrays.

In [7]:
z=x+y
z

tensor([4, 6])

### Convert from PyTorch to Numpy and vice versa.

In [8]:
z=z.numpy()
z

array([4, 6])

In [9]:
z=torch.from_numpy(z)
z

tensor([4, 6])

Good thing about these conversions is that these operations do not affect the code performance. Numpy and Pytorch saves the data in almost the same way in the memory and hence Pytorch can reuse the work done by Numpy.



## Multi-dimensional Tensors

Tensors are just n-dimensional number (including booleans) containers. YOu can get more details about Tensor at at [PyTorch's Tensor Docs](https://pytorch.org/docs/stable/tensors.html).

We have already created tensors. Now let's see how can we build n-dimensional tensors. 

In [10]:
a= torch.tensor([[1, 2], [3, 4]])
a

tensor([[1, 2],
        [3, 4]])

We can define type of tensor as:

In [11]:
a=torch.FloatTensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

Another way can be:

In [12]:
a=torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
a

tensor([[1., 2.],
        [3., 4.]])

We can create matrices of random numbers, O's, 1's and identity matrices as:

In [13]:
rand_mat=torch.rand(4,3)
rand_mat

tensor([[0.9471, 0.5586, 0.4430],
        [0.4474, 0.1853, 0.2681],
        [0.1750, 0.5708, 0.7609],
        [0.6340, 0.4863, 0.1911]])

In [14]:
ones_mat=torch.ones(3,4)
ones_mat

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
zeros_mat=torch.zeros(3,4)
zeros_mat

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
identity_mat=torch.eye(4)
identity_mat

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

PyTorch has several useful operations as shown below:

In [17]:
x = torch.rand(2, 3) 
y = torch.rand(2, 3)  
z = torch.add(x, y) 

z

tensor([[0.4868, 0.9866, 1.2861],
        [1.6993, 0.9130, 0.9724]])

Another way to assign outout to a variable is given below:

In [18]:
torch.add(x, y, out=z)
z

tensor([[0.4868, 0.9866, 1.2861],
        [1.6993, 0.9130, 0.9724]])

### In-place operation

All operations end with “_” is in place operations:

In [19]:
z_1=x.add_(y)   # same results as in above expression
z_1

tensor([[0.4868, 0.9866, 1.2861],
        [1.6993, 0.9130, 0.9724]])

Generally, performing some operation creates a new Tensor, just like z_2 was created in above expression. We can use in-place to assign value to same variable:

In [20]:
print ('value of x is:',x)
x.add_(y)
print ('updated value of x is:',x)


value of x is: tensor([[0.4868, 0.9866, 1.2861],
        [1.6993, 0.9130, 0.9724]])
updated value of x is: tensor([[0.7824, 1.6582, 1.8156],
        [2.4036, 1.5551, 1.3320]])


### Transpose of a tensor
Transpose of a tensor can be taken as follows:

In [21]:
x.t()

tensor([[0.7824, 2.4036],
        [1.6582, 1.5551],
        [1.8156, 1.3320]])

### Tensor meta-data
Size of the Tensor and number of elements in Tensor:

In [22]:
x_size=x.size()                        
total_elements=torch.numel(x)
print ('size of x is:', x_size)
print ('total number of elements in x are:', total_elements)

size of x is: torch.Size([2, 3])
total number of elements in x are: 6


### Reshaping a Tensor
Tensors can be reshaped to any shape as:

In [23]:
### Tensor resizing
x = torch.randn(2, 3)            # Size 2x3
print ('original x is:', x)
y = x.view(6)                    # Resize x to size 6- a single row having 6 elements
print ('reshaped x is:', y)


original x is: tensor([[ 1.3211, -0.4986,  0.2360],
        [ 1.1495,  1.7325, -0.8947]])
reshaped x is: tensor([ 1.3211, -0.4986,  0.2360,  1.1495,  1.7325, -0.8947])


## Running the code on GPU

At this point, you might be like: "Why do I need PyTorch at all? All of this is perfectly doable with NumPy?". PyTorch has three major superpowers: 
- you can run your operations on the GPU(s) (or something else)
- [Autograd: automatic differentiation](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)
- A set of tools to build Neural Networks. Including several additional packages for working [with text](https://github.com/pytorch/text) or [images](https://github.com/pytorch/vision).

Doing your Deep Learning computations on the GPU speeds up your experiment by a lot! And PyTorch makes it ridiculously easy to do it. Let's start by checking if GPU is available:

In [24]:
device=torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [25]:
torch.cuda.is_available()

True

In [26]:
torch.cuda.current_device()

0

Good, we have a [CUDA](https://en.wikipedia.org/wiki/CUDA)-enabled GPU device on our hands. Let's store a Tensor on it:

In [28]:
x = torch.tensor([[2, 3], [1, 2]])
print ('x without gpu= ', x)
x=x.to(device)
print ('x with gpu= ', x)

x without gpu=  tensor([[2, 3],
        [1, 2]])
x with gpu=  tensor([[2, 3],
        [1, 2]], device='cuda:0')


Now we can do normal operations with these Tensors just like we did before:

In [32]:
y = torch.tensor([[1, 2], [3, 1]])
y = y.to(device)

In [33]:
x.add(y)

tensor([[3, 5],
        [4, 3]], device='cuda:0')

Please note that we will need to shift 'y' to GPU too if we want to add 'x' with 'y'.