In [1]:
try:
    import torch
except ImportError as e:
    print ('installing PyTorch')
    !pip install -q -U torch watermark  # module doesn't exist, deal with it.
    


In [ ]:
# for pep-8
!pip install nb_black
!pip install pycodestyle_magic
!pip install pycodestyle
!pip install flake8

In [1]:
%load_ext nb_black
%load_ext pycodestyle_magic

<IPython.core.display.Javascript object>

Pytorch is an open source machine learning framework that accelerates the path from research prototyping to production deployment.

## PyTorch ❤ NumPy

Pytorch is similar to Numpy. If you have good skills in Numpy then Pytorch will be a piece of cake for you. If not, don't worry, you will learn along the way!!

Let's start with something simple:

In [2]:
import torch
import numpy as np

<IPython.core.display.Javascript object>

In [3]:
%reload_ext watermark
%watermark -v -p numpy,torch

Python implementation: CPython
Python version       : 3.8.0
IPython version      : 8.3.0

numpy: 1.22.3
torch: 1.11.0+cu113



<IPython.core.display.Javascript object>

In [4]:
x = np.array([1, 2])
y = np.array([3, 4])

<IPython.core.display.Javascript object>

In [5]:
x, y

(array([1, 2]), array([3, 4]))

<IPython.core.display.Javascript object>

In [6]:
z = x + y
z

array([4, 6])

<IPython.core.display.Javascript object>

Now let's do the same thing using Pytorch!!

In [7]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
x, y

(tensor([1, 2]), tensor([3, 4]))

<IPython.core.display.Javascript object>

Now we can simply add these 2 just like we did in the case of Numpy arrays.

In [8]:
z = x + y
z

tensor([4, 6])

<IPython.core.display.Javascript object>

### Convert from PyTorch to Numpy and vice versa.

In [9]:
z = z.numpy()
z

array([4, 6])

<IPython.core.display.Javascript object>

In [10]:
z = torch.from_numpy(z)
z

tensor([4, 6])

<IPython.core.display.Javascript object>

Good thing about these conversions is that these operations do not affect the code performance. Numpy and Pytorch saves the data in almost the same way in the memory and hence Pytorch can reuse the work done by Numpy.



## Multi-dimensional Tensors

Tensors are just n-dimensional number (including booleans) containers. YOu can get more details about Tensor at at [PyTorch's Tensor Docs](https://pytorch.org/docs/stable/tensors.html).

We have already created tensors. Now let's see how can we build n-dimensional tensors. 

In [11]:
a = torch.tensor([[1, 2], [3, 4]])
a

tensor([[1, 2],
        [3, 4]])

<IPython.core.display.Javascript object>

We can define type of tensor as:

In [12]:
a = torch.FloatTensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

<IPython.core.display.Javascript object>

Another way can be:

In [13]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
a

tensor([[1., 2.],
        [3., 4.]])

<IPython.core.display.Javascript object>

We can create matrices of random numbers, O's, 1's and identity matrices as:

In [14]:
rand_mat = torch.rand(4, 3)
rand_mat

tensor([[0.4056, 0.2458, 0.2037],
        [0.1310, 0.5465, 0.3545],
        [0.5503, 0.7099, 0.9430],
        [0.1699, 0.3394, 0.3849]])

<IPython.core.display.Javascript object>

In [15]:
ones_mat = torch.ones(3, 4)
ones_mat

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

<IPython.core.display.Javascript object>

In [16]:
zeros_mat = torch.zeros(3, 4)
zeros_mat

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

<IPython.core.display.Javascript object>

In [17]:
identity_mat = torch.eye(4)
identity_mat

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

<IPython.core.display.Javascript object>

PyTorch has several useful operations as shown below:

In [18]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
z = torch.add(x, y)

z

tensor([[1.5686, 1.2156, 1.4334],
        [1.7019, 1.1217, 1.5503]])

<IPython.core.display.Javascript object>

Another way to assign outout to a variable is given below:

In [19]:
torch.add(x, y, out=z)
z

tensor([[1.5686, 1.2156, 1.4334],
        [1.7019, 1.1217, 1.5503]])

<IPython.core.display.Javascript object>

### In-place operation

All operations end with “_” is in place operations:

In [20]:
z_1 = x.add_(y)  # same results as in above expression
z_1

tensor([[1.5686, 1.2156, 1.4334],
        [1.7019, 1.1217, 1.5503]])

<IPython.core.display.Javascript object>

Generally, performing some operation creates a new Tensor, just like z_2 was created in above expression. We can use in-place to assign value to same variable:

In [21]:
print ('value of x is:',x)
x.add_(y)
print ('updated value of x is:',x)


value of x is: tensor([[1.5686, 1.2156, 1.4334],
        [1.7019, 1.1217, 1.5503]])
updated value of x is: tensor([[2.2741, 1.7544, 2.1129],
        [2.6785, 1.3158, 2.2525]])


<IPython.core.display.Javascript object>

### Transpose of a tensor
Transpose of a tensor can be taken as follows:

In [22]:
x.t()

tensor([[2.2741, 2.6785],
        [1.7544, 1.3158],
        [2.1129, 2.2525]])

<IPython.core.display.Javascript object>

### Tensor meta-data
Size of the Tensor and number of elements in Tensor:

In [23]:
x_size = x.size()
total_elements = torch.numel(x)
print("size of x is:", x_size)
print("total number of elements in x are:", total_elements)

size of x is: torch.Size([2, 3])
total number of elements in x are: 6


<IPython.core.display.Javascript object>

### Reshaping a Tensor
Tensors can be reshaped to any shape as:

In [24]:
### Tensor resizing
x = torch.randn(2, 3)            # Size 2x3
print ('original x is:', x)
y = x.view(6)                    # Resize x to size 6- a single row having 6 elements
print ('reshaped x is:', y)


original x is: tensor([[ 0.5639,  0.8304, -1.7485],
        [-1.6687,  0.5272, -0.0970]])
reshaped x is: tensor([ 0.5639,  0.8304, -1.7485, -1.6687,  0.5272, -0.0970])


<IPython.core.display.Javascript object>

## Running the code on GPU

At this point, you might be like: "Why do I need PyTorch at all? All of this is perfectly doable with NumPy?". PyTorch has three major superpowers: 
- you can run your operations on the GPU(s) (or something else)
- [Autograd: automatic differentiation](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)
- A set of tools to build Neural Networks. Including several additional packages for working [with text](https://github.com/pytorch/text) or [images](https://github.com/pytorch/vision).

Doing your Deep Learning computations on the GPU speeds up your experiment by a lot! And PyTorch makes it ridiculously easy to do it. Let's start by checking if GPU is available:

In [25]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

<IPython.core.display.Javascript object>

In [26]:
torch.cuda.is_available()

True

<IPython.core.display.Javascript object>

In [27]:
torch.cuda.current_device()

0

<IPython.core.display.Javascript object>

Good, we have a [CUDA](https://en.wikipedia.org/wiki/CUDA)-enabled GPU device on our hands. Let's store a Tensor on it:

In [28]:
x = torch.tensor([[2, 3], [1, 2]])
print("x without gpu= ", x)
x = x.to(device)
print("x with gpu= ", x)

x without gpu=  tensor([[2, 3],
        [1, 2]])
x with gpu=  tensor([[2, 3],
        [1, 2]], device='cuda:0')


<IPython.core.display.Javascript object>

Now we can do normal operations with these Tensors just like we did before:

In [29]:
y = torch.tensor([[1, 2], [3, 1]])
y = y.to(device)

<IPython.core.display.Javascript object>

In [30]:
x.add(y)

tensor([[3, 5],
        [4, 3]], device='cuda:0')

<IPython.core.display.Javascript object>

Please note that we will need to shift 'y' to GPU too if we want to add 'x' with 'y'.